version: '3.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config/
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: local.kibana.org
  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipelines:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5045:5045
    command: "--config.reload.automatic"


volumes:
  data01: